FROM node:19-alpine3.16


WORKDIR /server

ADD /server/package.json /server/package.json
ADD /server/package-lock.json /server/package-lock.json
ADD /server/tsconfig.json /server/tsconfig.json
ADD /server/tsconfig.build.json /server/tsconfig.build.json
ADD /server/nest-cli.json /server/nest-cli.json

RUN npm install
CMD npm run start:dev