version: '3.8'
services:
  external-data-server:
    container_name:  external-data-server
    restart: on-failure:3
    image: dev/dockerfile
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    build:
        context: ../
        dockerfile: docker/dev/dockerfile
    volumes:
      - ../server/src:/server/src