version: '3.8'
services:
  user-server:
    container_name:  user-server
    restart: on-failure:3
    image: dev/dockerfile
    environment:
      - PORT=3333
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    build:
        context: ../
        dockerfile: docker/dev/dockerfile
    volumes:
      - ../server/src:/server/src